# .streamlit/secrets.toml
OPENAI_API_KEY = "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"